# .streamlit/secrets.toml
OPENAI_API_KEY = "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"